# .streamlit/secrets.toml
OPENAI_API_KEY = "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"